# .streamlit/secrets.toml
OPENAI_API_KEY = "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"